# .streamlit/secrets.toml
OPENAI_API_KEY = "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"